controller_list:
  - name: fake_left_hand_controller
    joints:
      - hand_left_index_joint0
      - hand_left_little_joint1
      - hand_left_little_joint2
      - hand_left_little_joint0
      - hand_left_index_joint1
      - hand_left_index_joint2
      - hand_left_middle_joint0
      - hand_left_middle_joint1
      - hand_left_middle_joint2
      - hand_left_ring_joint0
      - hand_left_ring_joint1
      - hand_left_ring_joint2
      - hand_left_thumb_joint0
      - hand_left_thumb_joint1
      - hand_left_thumb_joint2
  - name: fake_right_hand_controller
    joints:
      - hand_right_index_joint0
      - hand_right_index_joint1
      - hand_right_index_joint2
      - hand_right_little_joint0
      - hand_right_little_joint1
      - hand_right_little_joint2
      - hand_right_middle_joint0
      - hand_right_middle_joint1
      - hand_right_middle_joint2
      - hand_right_ring_joint0
      - hand_right_ring_joint1
      - hand_right_ring_joint2
      - hand_right_thumb_joint0
      - hand_right_thumb_joint1
      - hand_right_thumb_joint2