<?xml version="1.0"?>
<robot name="ice_cream_trays" 
xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- <xacro:include filename="$(find scooping_cv)/models/ice_cream_trays.gazebo"/> -->
<xacro:include filename="$(find scooping_cv)/models/zed_camera_gazebo.gazebo"/>

<!--__________CONSTANTS__________-->
<xacro:property name="deg_to_rad" value="0.01745329251994329577"/>

<!--__________VARIABLES__________-->
<xacro:property name= "baseline" value="0.65" />
<xacro:property name= "tray_length" value="0.36"/>
<xacro:property name= "tray_width" value="0.165"/>
<xacro:property name= "tray_height" value="0.12"/>
<xacro:property name= "baseline" value="0.12" />
<xacro:property name= "camera_size" value="0.01"/>


<!--__________LINKS____________-->
	<link name= "world"/> <!--fixed world link-->

	<link name= "base_link">
		<visual>
			<geometry>
				<box size="0.1 0.1 0.1"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0.05"/>
			<material name="white"/> 
		</visual>

		<inertial>
			<mass value="1"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</inertial>

		<collision>
			<geometry>
				<box size="0.1 0.1 0.1"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0.05"/>
		</collision>
	</link>

	<link name= "vanilla_link">
		<visual>
			<geometry>
				<!-- <box size="${tray_width} ${tray_length} ${tray_height}"/> -->
				<mesh filename="package://scooping_cv/meshes/ice_cream_tray_vanilla.dae"/>

			</geometry>
			<origin rpy="0 0 ${deg_to_rad*90}" xyz="${tray_width/2} ${-tray_length/2} ${-tray_height/2}"/>
			<material name="white"/>
		</visual>

		<inertial>
			<mass value="1e-5"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</inertial>

		<collision>
			<geometry>
				<box size="${tray_width} ${tray_length} ${tray_height}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</collision>
	</link>

    <link name= "chocolate_link">
		<visual>
			<geometry>
				<!-- <box size="${tray_width} ${tray_length} ${tray_height}"/> -->
				<mesh filename="package://scooping_cv/meshes/ice_cream_tray_chocolate.dae"/>
			</geometry>
			<origin rpy="0 0 ${deg_to_rad*90}" xyz="${tray_width/2} ${-tray_length/2} ${-tray_height/2}"/>
			<material name="white"/>
		</visual>

		<inertial>
			<mass value="1e-5"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</inertial>

		<collision>
			<geometry>
				<box size="${tray_width} ${tray_length} ${tray_height}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</collision>
	</link>

	<link name= "cam_left_link">
		<visual>
			<geometry>
				<box size="${camera_size} ${camera_size} ${camera_size}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<material name="white"/>
		</visual>

		<inertial>
			<mass value="1e-5"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</inertial>

		<collision>
			<geometry>
				<box size="${camera_size} ${camera_size} ${camera_size}"/>
			</geometry>
			<origin rpy="0 0 ${deg_to_rad *90}" xyz="0 0 0"/>
		</collision>
	</link>

	<link name= "cam_right_link">
		<visual>
			<geometry>
				<box size="${camera_size} ${camera_size} ${camera_size}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<material name="white"/>
		</visual>

		<inertial>
			<mass value="1e-5"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</inertial>

		<collision>
			<geometry>
				<box size="${camera_size} ${camera_size} ${camera_size}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</collision>
	</link>

<!--___________JOINTS___________-->
	<joint name= "fixed_joint" type="fixed">
		<parent link="world"/>
		<child link="base_link"/>
   		<origin xyz="0 0 0"/>
	</joint>

	<joint name= "joint1" type="continuous">
		<parent link="base_link"/>
		<child link="vanilla_link"/>
		<origin xyz="${-tray_width/2} 0 0.5" rpy="0 0 ${0}"/>
		<axis xyz="0 0 1" rpy="0 0 0"/>
	</joint>

	<joint name= "joint2" type="continuous">
		<parent link="base_link"/>
		<child link="chocolate_link"/>
		<origin xyz="${tray_width/2} 0 0.5" rpy="0 0 ${0}"/>
		<axis xyz="0 0 1"/>
	</joint>

		<joint name= "joint_cam_left" type="continuous">
		<parent link="base_link"/>
		<child link="cam_left_link"/>
		<origin xyz="${-(baseline/2)} -0.4 1" rpy="0 ${deg_to_rad*40} ${deg_to_rad*90}"/>
<!--		<origin xyz="${-(baseline/2)} ${-triangle_height/2} 0.5" rpy="0 0 ${deg_to_rad*120}"/>-->
<!--		<origin xyz="${-(baseline/2)} ${-triangle_height/2} 0.5" rpy="0 0 ${deg_to_rad*150}"/>-->
		<axis xyz="0 0 1" rpy="0 0 0"/>
	</joint>

	<joint name= "joint_cam_right" type="continuous">
		<parent link="base_link"/>
		<child link="cam_right_link"/>
<!--		<origin xyz="${baseline/2} ${-triangle_height/2} 0.5" rpy="0 0 ${deg_to_rad*30}"/>-->
<!--		<origin xyz="${baseline/2} ${-triangle_height/2} 0.5" rpy="0 0 ${deg_to_rad*60}"/>-->
		<origin xyz="${baseline/2} -0.4 1" rpy="0 ${deg_to_rad*40} ${deg_to_rad*90}"/>
		<axis xyz="0 0 1"/>
	</joint>


</robot>

